# Generated by Django 4.2.8 on 2023-12-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower_data',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
