# Generated by Django 4.2.8 on 2023-12-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers_base', '0002_alter_flower_data_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_data',
            name='admin_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='flower_class',
            name='class_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='flower_class',
            name='class_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='flower_data',
            name='flower_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='flower_data',
            name='flower_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
