# Generated by Django 4.2.8 on 2023-12-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers_base', '0003_alter_admin_data_admin_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower_data',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
