# Generated by Django 4.2.8 on 2023-12-19 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flowers_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_id', models.IntegerField()),
                ('outbound_num', models.IntegerField()),
                ('outbound_date', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flowers_base.admin_data')),
                ('flowers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers_base.flower_class')),
            ],
        ),
        migrations.CreateModel(
            name='inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_id', models.IntegerField()),
                ('inbound_num', models.IntegerField()),
                ('inbound_date', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flowers_base.admin_data')),
                ('flowers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers_base.flower_class')),
            ],
        ),
    ]
