# Generated by Django 4.2.8 on 2023-12-19 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers_base', '0003_alter_admin_data_admin_id_and_more'),
        ('flowers_transcaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='flowers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers_base.flower_data'),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='flowers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers_base.flower_data'),
        ),
    ]
