# Generated by Django 4.2.8 on 2023-12-20 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers_base', '0004_alter_flower_data_price'),
        ('flowers_transcaction', '0002_alter_inbound_flowers_alter_outbound_flowers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='flowers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers_base.flower_data', to_field='flower_name'),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='flowers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers_base.flower_data', to_field='flower_name'),
        ),
    ]
