# Generated by Django 4.2.8 on 2023-12-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers_transcaction', '0004_alter_inbound_inbound_id_alter_outbound_outbound_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='inbound_id',
            field=models.BigIntegerField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='inbound_num',
            field=models.IntegerField(max_length=16),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='outbound_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
